### PR TITLE
Recreate home assistant plugin

### PR DESCRIPTION
**Pull request by provokateurin**
See #11

### CODE REVIEW

**Comment by provokateurin** [comment]
@n8henrie Do you have any interests in this pull request? Please respond.

**Comment by n8henrie** [comment]
Yes, I have pulled it into my local dev branch but haven't pushed the
changes because it was not working locally.

Of note, I think this could all be done with the existing RESTAPIPlugin,
but this does make it more convenient.

Nate

**Comment by provokateurin** [comment]
The REST API got deprecated recently.
I'm closing this pull request, because I will rework the code based on the dev branch.

**Comment by n8henrie** [comment]
The REST API
<https://developers.home-assistant.io/docs/en/external_api_rest.html> was
deprecated? I thought the Python API
<https://developers.home-assistant.io/docs/en/external_api_rest_python.html>
was deprecated.

No need to rework the PR right now, I've already moved it into dev and have
made several changes, I recommend waiting until my changes are pushed out,
probably next week. I just need some time to make sure they're working with
Alexa locally.

**Comment by provokateurin** [comment]
Yes the python API got deprecated.
I wanted to fix the formatting errors, but messed up my git.
For me they worked locally with Alexa.

**Pull request closed without merging**
