### PR TITLE
MQTT plugin: optionally set client id

### PR DESCRIPTION
**Pull request by flavio-fernandes**
Set client id when provided in MQTT plugin's json config.

### CODE REVIEW

**Comment by n8henrie** [comment]
Cool, thanks!

**Comment by n8henrie** [comment]
Thanks for including a test!

Have you checked to make sure this doesn't break compatibility or change behavior when the client_id is unset? I don't use any mqtt devices with Fauxmo to test with.

**Comment by flavio-fernandes** [comment]
> Thanks for including a test!

Np. Thank you for creating the mqtt plugin! ;)

>
> Have you checked to make sure this doesn't break compatibility or change behavior when the client_id is unset? I don't use any mqtt devices with Fauxmo to test with.

Yes! I use it against mosquito broker w/out any problems with and w/out the client id.

**Comment by n8henrie** [comment]
> Thank you for creating the mqtt plugin!

I wish I could take credit, but it was another contributor such as yourself.

> I use it against mosquito broker w/out any problems with and w/out the
client id.

Sounds great, will merge soon.

**Comment by n8henrie** [comment]
Sorry for the delay. Thanks again @flavio-fernandes!

**Pull request merged**
